# Generated by Django 6.1.1 on 2026-09-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
