# Generated by Django 6.1.1 on 2026-09-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_question_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="image_url",
        ),
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="questions/"),
        ),
    ]
