# Generated by Django 6.1.1 on 2026-09-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_question_image_url_question_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="image_url",
        ),
        migrations.AddField(
            model_name="answer",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="answers/"),
        ),
    ]
